### ISSUE TITLE
Animation needs to be stopped before playing another

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#132]
An entity has two animations, you play the first one (that doesn't loop) and then you try to play the second one, but it doesn't work.

The ugly workaround is to explicitly stop the first animation (which shouldn't be necessary because it doesn't loop), and then play the second one.

Here's a code example that Pato built showing the bug:

[anim_test 2.zip](https://github.com/decentraland/explorer/files/3121775/anim_test.2.zip)

**Comment by matiasbargas** [comment]
fix with https://github.com/decentraland/unity-client/issues/231
