### ISSUE TITLE
gltf/glb entities have wrong boundary-testing shapes

### ISSUE THREAD

**Issue by cfravel** [decentraland/kernel-legacy#136]
Summary: if you put a gltf entity next to, or even meters from, the boundary of a scene, it may still flash blue/red as if it is hanging over the boundary, and you can see that the visual indication of the bounding box is wrong.

As I had reported to dev a week or two ago, 5.0 scenes allowed gltf/glb vertices (but not their origin) to hang outside the scene.   6.0 seems to address this by putting a bounding container shape around a gltf/glb entity.
However in the first 6.0 release this gltf/glb bounding shape is too big and/or not properly centered on the glb mesh, so there are false "out of bounds" errors.

The attached scene demonstrates this

It contains one primitive box, and 3 instances of a glb cube.

The edge of the primitive box is tight against (0m from) the scene boundary, and is fine.

The first two glb cubes are, respectively, tight against the scene boundary, and 4m in both x and y from it, but are showing as out of bounds.  (But their bounding box indications are huge, not matching their actual boundaries).  Not until i get the cube about 8m from the boundaries is it ok.

**Comment by cfravel** [comment]
[demo-bounding-shape-bug.zip](https://github.com/decentraland/explorer/files/3125579/demo-bounding-shape-bug.zip)

**Comment by cfravel** [comment]
Here is another scene with a similar problem, although in this case the bounding shape seems reasonable, yet it flashes as if out of bounds.
[demo2-bounding-error.zip](https://github.com/decentraland/explorer/files/3125599/demo2-bounding-error.zip)

**Comment by cfravel** [comment]
Picture of the first example:

![image](https://user-images.githubusercontent.com/21015643/56871264-0d1be200-69e1-11e9-88f6-523928607037.png)

**Comment by cfravel** [comment]
Picture of the 2nd example

![image](https://user-images.githubusercontent.com/21015643/56871282-3ccaea00-69e1-11e9-8571-690f17ff96a6.png)

**Comment by cfravel** [comment]
In resolving this, if possible, please make it ok to put a cube or other such shape gltf/glb right against the edge of the scene, just not ok to hang at all past it.   if it cannot go right to the boundary, then a lot of my modular content will have to be resized slightly smaller and probably have a visible seam at a scene boundary.
I think this means like testing for the bounding shape to be <= boundary rather than < boundary.
Thanks

**Comment by cfravel** [comment]
And here is a good mystery in the 2nd example.
If I don't do the 180 rotation of her (to get her to face south), demonstrated by putting another instance of her same distance from the scene boundary, the unrotated instance doesn't warn!

const woman_GoldDress_3yYNfROogq0_1 = spawnGltfX(woman_GoldDressShape_3yYNfROogq0, 22, 0, 4, 0, 220, 0, 1, 1, 1)
const woman_GoldDress_3yYNfROogq0_2 = spawnGltfX(woman_GoldDressShape_3yYNfROogq0, 18, 0, 4, 0, 0, 0, 1, 1, 1)

![image](https://user-images.githubusercontent.com/21015643/56871367-46a11d00-69e2-11e9-8d1d-270b16fb6c28.png)

**Comment by matiasbargas** [comment]
To be reviewed when the unity client enforces boundaries and limits.
