### ISSUE TITLE
Improve DX by making compile process faster

### ISSUE THREAD

**Issue by fmiras** [decentraland/kernel-legacy#148]
# What? 

Try by using `ncc`, plain webpack or changing the decentraland-compiler approach. Refactor makefile to avoid rebuilding already built packages

# Why?

Waiting for compilation + tests takes **a lot** of time and slows the project development

**Comment by menduz** [comment]
We compile almost 100 projects with different configurations.. at this scale the only viable option is to manually tune the compiler, which is plain webpack.

ncc is for a different use case, we should remove it from the equation
