### ISSUE TITLE
Integrate profile service (S)

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#194]
Why? 

To help users manage their identity through different devices we need to sync profile data with our profile service. 

What? 

- [ ] Fetch user's profile from profile service
- [ ] Create a sync strategy for having local and remote information up to date

**Comment by fmiras** [comment]
This is too ambiguous, need more definition what does integrate profile service means? fetch the profile info when avatar appears? does this involves more than #215?

**Comment by BrianAmadori** [comment]
I think this may be a duplicate of #214 or vice-versa.

**Comment by moliva** [comment]
This issue depends on the profile service migration.
