### ISSUE TITLE
Filter tags to only publish SDK when needed

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#195]
Why? 

We publish a new version of the SDK with every GH Tag. This blocks us to deploy different versions of the explorer in `.zone` and `.today` envs

What?

Only publish SDK `decentraland-ecs@latest` version when the name of the tag starts with `SDK-`. `decentraland-ecs@next` should be updated with every `master` build as now.

**Comment by matiasbargas** [comment]
This is possible by using non-semver versions as tags.
