### ISSUE TITLE
Certified NFTs not working

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#20]
I believe this code used to work a couple of months ago. But not it doesn't work on @latest or on @next.

I'm supposed to be seeing a criptokitty here, but I don't see anything and don't get any error messages. I tried with a different token id and still nothing.

```
// create entity
const nft = new Entity()

// position entity
nft.add(new Transform({
  position: new Vector3(1, 1.2, 1)
  }))

// add an NFTShape, instanced with a token contract and token id
nft.add(new NFTShape("0x06012c8cf97bead5deae237070f9587f8e7a266d", "475577"))

// add entity to engine
engine.addEntity(nft)
```

**Comment by menduz** [comment]
NFTs are not working currently

**Comment by menduz** [comment]
@matiasbargas please define priorities regarding NFT

**Comment by menduz** [comment]
Post MVP

**Comment by nearnshaw** [comment]
We'll create a new ticket for this when we get to that point in the roadmap
