### ISSUE TITLE
Implement Avatar component

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/kernel-legacy#215]

**Comment by fmiras** [comment]
Correct me if I'm wrong @BrianAmadori: This involves creating an internal component like `entity.addComponent(new AvatarShape(userId))` that retrieves Avatar models info from profile service based on user ID

**Comment by BrianAmadori** [comment]
You are correct. But I'm not sure if we can embed the profile server fetching inside the Component logic because of the SDK event bindings. If we can't, we would have to fetch the profile service stuff directly from the Avatar's scene. This would be a bit nasty though.
