### ISSUE TITLE
Refactor entrypoints to include as less as possible debugging features on a production build

### ISSUE THREAD

**Issue by fmiras** [decentraland/kernel-legacy#243]
There are several development flags/features that are included in a production build such us `DEBUG`, `DEBUG_MESSAGES`, `DISABLE_AUTH`, `DEBUG_METRICS` URL flags and things like the WS connection for using Unity Editor, preview logic on explorer `tetra.html`

**Comment by eordano** [comment]
@fmiras feel free to reopen if this is not fixed yet
