### ISSUE TITLE
No "blank world" between loading the javascript code and rendering the first image

### ISSUE THREAD

**Issue by eordano** [decentraland/kernel-legacy#29]
Currently we're here:

a) We've got 1s of the screen with a spinning decentraland logo
b) Then, 8s with no models loaded ellapse
c) Then, 4s with a gray model with no textures
d) Then, we get an acceptable render

I'd like to be here:
a) 13s of spinning decentraland logo
b) Acceptable render

**Comment by menduz** [comment]
How many parcels should we load around the user?

**Comment by eordano** [comment]
At least the one the user is on, and the 8 around him

**Comment by menduz** [comment]
are you saying 8 + the user is on, forming a 3x3 square?

**Comment by cfravel** [comment]
some virtual worlds, like Second Life, put you in the scene as quickly as possible, even though not everything is visible yet.   It means that you can immediately see where you are, continue conversations with people you have teleported with, etc.

Most others give you a "loading" screen until everything looks good.  This is a terrible user experience, in my opinion.

Neither is fully immersive, but I can tell you from experience one gets used to gradual /delayed rendering, and in going between Second Life (and Decentraland) vs Sansar, High Fidelity, VR Chat, it is really annoying to be looking at a loading page when I could be starting to see, even to move aorund.

**Comment by cfravel** [comment]
https://client.decentraland.today/?position=-14%2C137
This is an 18 x 11 area, with 4 large scenes.

**Comment by eordano** [comment]
I disagree. I don't like Second Life's strategy for loading content. The feeling of "incompleteness" is pretty bad. I think that waiting for a few seconds before showing the user a complete experience is far better than an empty-loading-without-feedback world. Most of the folks in the team feel the same way.

Please note that this doesn't mean "until ALL assets are loaded". I believe every scene developer should have control over what does he/she think is "acceptable minimum content".

**Comment by menduz** [comment]
I think we could load a radius (8 peripherals and current parcel) and then keep the show-as-it-loads behavior for scenes outside the radius. Ideas @eordano ?

**Comment by eordano** [comment]
That sounds great @menduz

**Comment by cfravel** [comment]
seems like a fine compromise to me.
should only take a few seconds
