### ISSUE TITLE
Connection to web3 broken

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#390]
Scenes that use eth-connect have an issue trying to connect to Metamask.

The following scene that used to work is now broken:

https://github.com/decentraland-scenes/MANA-Transaction

The following error appears:

Error: Could not access eth_accounts: "Provider not set or invalid"

Baus in the community had this same error w a scene from his.

In this other scene that uses eth-connect, we get this different error:

https://github.com/decentraland-scenes/MANA-Burning-Altar

Uncaught (in promise) TypeError: Cannot read property 'sendAsync' of null
    at Object.t.sendAsync (preview.js:25)
    at c.sendAsync (preview.js:30)
    at v.processMessage (preview.js:25)
    at preview.js:25
    at Worker.<anonymous> (preview.js:25)

**Comment by tobeee** [comment]
Did this get fixed? Running into same issue
