### ISSUE TITLE
Handling of these foliage materials with alphas was broken between 2018-07-24 and 2018-08-10

### ISSUE THREAD

**Issue by fmiras** [decentraland/kernel-legacy#40]
Refer to https://github.com/decentraland/cli/issues/356

**Comment by cfravel** [comment]
Note that I'm seeing this materials rendering problem in SDK's "dcl start"
Because of another bug I have not been able to see this scene in the alpha client yet,.

**Comment by cfravel** [comment]
I really think that this needs to be addressed in the sdk first.
I'm seeing this in the SDK, not the client

**Comment by cfravel** [comment]
Some more information on this:
Regarding the "Large Amphitheater" as referred to in the original decentraland/cli#356 and which started having problems with some textures in July or August (without the model changing).
My modeller tried the experiment of attaching every piece of mesh together into one mesh, and the problem goes away.  It seems the client has some issue with large numbers of entities, some of which use the same textures, even if the numbers of things are within the SDK limits.
Having everything in one mesh isn't a great workaround.

You can probably reproduce this if you have a single gltf with a fairly large number of identical mesh objects, all of which use the same texture.  I only see the problem on textures that are .pngs with an alpha channel.

**Comment by cfravel** [comment]
This is very conspicuous in the trees scene of this Decentrland Conference Center prototype:
https://client.decentraland.today/?position=-19%2C141
