### ISSUE TITLE
Empty parcels: when a parcel has no scene, pick a random scene from a pool of placeholder scenes.

### ISSUE THREAD

**Issue by eordano** [decentraland/kernel-legacy#434]
### 1 pager: https://docs.google.com/document/d/1xwPXIUhItwhlqzgiwHuTuda-h-AL3swOlgqEleCqIDk/edit
This issue refers to **use case #2** only.

Added requirement: **do not apply this to empty parcels that are part of a district.**

**Comment by xpalaum** [comment]
Sharing the 1x1 scenes Mauri sent to me:
https://drive.google.com/open?id=1kuA7Es8G_h2iv9c85VLfUap3REDNApJ2
