### ISSUE TITLE
Scene Lifecycle: 30second timeout is always reached on teleport

### ISSUE THREAD

**Issue by eordano** [decentraland/kernel-legacy#437]
Currently, whenever the user teleports, it takes 30 seconds to show the new position. This looks like it's a consequence of Unity not sending the ActivateRenderingACK until the timeout is reached.

**Comment by BrianAmadori** [comment]
This might be due to the scenes taking too long to load. The 30 seconds cap can be a bit optimistic in plazas and such. Let's confirm this happens in empty/low size scenes.
