### ISSUE TITLE
Refactor teleport flow

### ISSUE THREAD

**Issue by pravusjif** [decentraland/kernel-legacy#438]
- Rename `SetPosition` message to `Teleport`
- Change player position before activating the engine rendering.

depends on
https://github.com/decentraland/unity-client/issues/777

**Comment by eordano** [comment]
Shouldn't we do this on the kernel side? Wait for DeactivateRenderingACK before sending the teleport??

**Comment by moliva** [comment]
@eordano Yes, that's the idea. But as of today, we are block by https://github.com/decentraland/unity-client/issues/777 to be able to do so, it errs as the `CharacterController` cannot be found.
