### ISSUE TITLE
Add a `reset()` to animation clips

### ISSUE THREAD

**Issue by fmiras** [decentraland/kernel-legacy#51]
Today to reset an animation I have to delete the previous one and create another:
```ts
// It lasts 2 seconds
const walkClip = new AnimationClip('walk')
walkClip.play()
setTimeout(() => walk.pause(), 1000)
// reset
const walkClip2 = new AnimationClip('walk')
// Use the new animation
walkClip2.play()
```

Developers should be able to reset existing ones:
```ts
const walkClip = new AnimationClip('walk')
walkClip.play()
setTimeout(() => walkClip.pause() && walkClip.reset(), 1000)
// Use it again
walkClip.play()
```

**Comment by michaltakac** [comment]
Can we call `.pause()` inside the `.reset()` method?

**Comment by fmiras** [comment]
@michaltakac what do you mean? can you give an example?

**Comment by michaltakac** [comment]
I mean that `walkClip.reset()` would do `walkClip.pause() && walkClip.reset()` in one take.
