### ISSUE TITLE
Loading of Roads and Empty parcels show no benefit from caching

### ISSUE THREAD

**Issue by xpalaum** [decentraland/kernel-legacy#518]
After walking around through tens of empty parcels, they take the same amount of time to load as before. With proper caching, I would expect them to be already loaded when coming to sight.

**Comment by BrianAmadori** [comment]
They are cached correctly. This may be related with the perception of loading time that is skewed by the random delay we are applying to mesh instancing to avoid stutters. Also, the green blockers spawned by roads/default scenes don't help. 

Another case is when the player spawns inside a plaza. In this case, the roads/default scenes aren't cached until the first time they are met. So, the player'd have to wait for them to load until the caching benefits are seen. A possible improvement to this would be to load the roads/default scenes' assets in advance, regardless of where the player is when she inits the client.
