### ISSUE TITLE
Green Walls still not disappearing in some cases

### ISSUE THREAD

**Issue by xpalaum** [decentraland/kernel-legacy#519]
/goto 10,90
After teleporting to one of the Plazas, I appeared in a parcel that was not loaded, that is, I was standing on "the grid", and most of the surrounding objects were still loading. The green walls stood up in most surrounding parcels, not going away for minutes until I stopped testing.

**Comment by BrianAmadori** [comment]
I just teleported to 0,0 and 10,90 many times like crazy (including other locations too) and I can't seem to be able to reproduce this. I'd need more specific steps.
