### ISSUE TITLE
Emit custom events in a scene

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#68]
The `Engine` object has methods to create custom events and instance event listeners, but these methods aren't exposed to SDK users.

It would be useful for developers building scenes if they could use these same methods to generate custom events and listeners for them in their scenes. For example, the scene code would create an event each time an enemy is killed, and this event could be handled by a system that updates the user's score.

From our discussions with Agus, there's an unnecessary argument that could be removed, I believe in the method that instances a listener (please confirm with Agus).

**Comment by menduz** [comment]
The `listener` parameter was not removed. An example was added here: https://github.com/decentraland/explorer/pull/106
