### ISSUE TITLE
Fixed UI

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#95]
Currently, the UI is only meant for pop-up screens that take up a significant part of your view and don't let you interact with the world again until you close them.

We want the ability to add a smaller UI that's always there while you're in a scene. This UI isn't meant for interacting, just to show information such as health, score, experience points, etc.

Open questions:
- We need to define what space we want to limit this UI to
- Can it be closed?
- Will there be a separate kind of screenspace component for it? A setting in the existing screenspace component to set the type?

One pager: https://docs.google.com/document/d/1dvDvN5uFFS1UJbtlOfgRg9lEKVivKY8_HVlbZHQDhMQ/edit#heading=h.oynehbm48jrc

**Comment by eordano** [comment]
Can we mark this as done? @nearnshaw

**Comment by nearnshaw** [comment]
This has been fixed already, let's close it!
